env:
  FORCE_COLOR: 1

freebsd_task:
  freebsd_instance:
    matrix:
      - image: freebsd-10-4-release-amd64
      - image_family: freebsd-11-4
      - image_family: freebsd-12-1
      # - image_family: freebsd-13-0-snap
  install_script: pkg install -y dash bash zsh ksh93 mksh oksh
  prepare_script:
    - ./shellspec --task fixture:stat:prepare
  script:
    - contrib/all.sh contrib/various_test.sh

gitbash_task:
  timeout_in: 120m
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $ProgramFiles\Git\bin;$PATH
  install_script:
    - git --version
  prepare_script:
    - bash -c "env | grep -E '^(LC_|LANG|CYGWIN|MSYS)'"
    - bash -c "mount"
    - bash -c "./shellspec --task fixture:stat:prepare"
  script:
    - bash -c "contrib/all.sh shellspec"

msys_task:
  timeout_in: 120m
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\msys64\usr\bin;$PATH
  install_script:
    - choco install -y --no-progress msys2
    - pacman.exe -Syu --noprogressbar --noconfirm
    - pacman.exe -S --noprogressbar --noconfirm dash bash busybox mksh zsh
    - pacman.exe -Q
  prepare_script:
    - bash -c "env | grep -E '^(LC_|LANG|CYGWIN|MSYS)'"
    - bash -c "mount"
    - bash -c "./shellspec --task fixture:stat:prepare"
  script:
    - bash -c "contrib/all.sh shellspec"

cygwin_task:
  timeout_in: 120m
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\cygwin\bin;$PATH
  install_script:
    - choco install -y --no-progress cygwin cyg-get
    - cyg-get nc dash bash busybox mksh posh zsh
    - cygcheck -c
  prepare_script:
    - bash -c "env | grep -E '^(LC_|LANG|CYGWIN|MSYS)'"
    - bash -c "mount"
    - bash -c "./shellspec --task fixture:stat:prepare"
    # I don't know why but tests using below files fail in cirrus ci environment.
    - bash -c "rm -f ./spec/fixture/stat/{readable,writable}"
  script:
    - bash -c 'contrib/all.sh shellspec'

busybox_task:
  timeout_in: 120m
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  install_script:
    - choco install -y --no-progress busybox
  script:
    - busybox ash -c "contrib/all.sh shellspec"
