#!/bin/sh -eux

docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .. \
  --build-arg CREATED="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --build-arg AUTHORS="$AUTHORS" \
  --build-arg VERSION="$(../shellspec --version)" \
  --build-arg REVISION="$(git rev-parse --short HEAD)" \
  --build-arg REFNAME="$DOCKER_TAG"
