#!/bin/sh -eux

# IMAGE_NAME ($DOCKER_REPO:$DOCKER_TAG)
#   shellspec/shellspec:<TAG>
#   shellspec/shellspec-<VARIANT>:<VERSION>

case $DOCKER_REPO in
  *-scratch) exit
esac

# Build kcov image
case $DOCKER_TAG in
  latest) IMAGE_NAME="$DOCKER_REPO:kcov" ;;
  *     ) IMAGE_NAME="$IMAGE_NAME-kcov" ;;
esac
docker build --target kcov -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .. \
  --build-arg CREATED="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --build-arg VERSION="$(../shellspec --version)" \
  --build-arg REVISION="$(git rev-parse --short HEAD)" \
  --build-arg REFNAME="$DOCKER_TAG"
